### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by anavalikhina** [price0416/DEvis#4]
I am trying to install the package with devtools from GitHub, and got 404 error.

devtools::install_github("price0416/DEvis/DEvis")

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`price0416`) and repo name (`DEvis`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by msierk** [comment]
The V's in DEVis need to be capitalized - install_github command in the README should be fixed...

**Comment by anavalikhina** [comment]
devtools::install_github("price0416/DEvis/DEVis")

One small one capital. Really?)) Maybe, you have to decide on the precise name of the package too)

**Comment by reemelkabbout** [comment]
Try this one it worked for me.
devtools::install_github("price0416/DEvis/DEVis")

**Comment by AOHD** [comment]
This is still not stated correctly on the readme. You have to go to this issue to figure out how to install the package.

**Comment by faridbge** [comment]
> Try this one it worked for me. devtools::install_github("price0416/DEvis/DEVis")

It worked really. I have not noticed two different "v" and "V".
Still they have not changed in README file !!!!
